### ISSUE TITLE
windows 7

### ISSUE THREAD

**Issue by ArtsemK** [blackholeearth/Win10_BrightnessSlider#23] opened 2018-08-25 22:44 UTC
There are doesn't works switching brightness with the keys on the keyboard in my laptop on windows 7.

Dear, make your slider for windows 7.

Much thx

**Comment by blackholeearth** [comment] 2018-08-26 11:32
there is no keyboard shortcut  feature in tihs app.  ( ie ; ctrl+UP Arrow)

*if you mean FN key on keyboard  . it is not easy. it may be even impossible.

duplicate of  #4

**Closed** 2018-08-26 11:33 UTC

**Comment by ArtsemK** [comment] 2018-08-27 00:43
I mean that there are no drivers in my laptop to change the brightness level using fn+f2/f3. 
This does not refer to your app.
Your app is the only way for me to change the brightness level easily in this case.
But my OS is Windows 7, not Windows 10 (your app is for Windows 10).
So it will be nice if you make your Brightness Slider for Windows 7.
Thx

**Comment by ArtsemK** [comment] 2018-08-28 16:12
ok, dear, i'm so sorry, works nice on my windows 7, you may close the issue.
thx

**Comment by ArtsemK** [comment] 2018-08-30 17:51
it may be interesting
![default](https://user-images.githubusercontent.com/36735077/44869501-6a1a9900-ac96-11e8-888e-b6c3662135ae.png)

**Comment by ArtsemK** [comment] 2018-09-16 16:40
it would be nice if the brightness changed from pressing (right mouse button) + wheel.

the app "volume2" changes volume level from pressing (right mouse button) + wheel - it is very convenient.
