### ISSUE TITLE
Unhandled exception when debugging the project

### ISSUE THREAD

**Issue by Hendrik-Koelbel** [blackholeearth/Win10_BrightnessSlider#56] opened 2019-12-06 11:46 UTC
Is Intel Graphics 630 not supported with the Terra 6236 W monitor?
This error only occurs when debugging the application yourself. When I use your compiled application, everything works perfectly.

```
System.Management.ManagementException
  HResult=0x80131501
  Message = Not supported
  Quelle = System.Management
  Stack monitoring:
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObjectCollection.ManagementObjectEnumerator.MoveNext()
   at Win10_BrightnessSlider.Form1.GetBrightness() in C:\Users\xxx\Desktop\Win10_BrightnessSlider-master\Win10_BrightnessSlider\Form1.cs: Zeile201
   at Win10_BrightnessSlider.Form1.UpdateStatesOnGuiControls() in C:\Users\xxx\Desktop\Win10_BrightnessSlider-master\Win10_BrightnessSlider\Form1.cs: Zeile101
   at Win10_BrightnessSlider.Form1.Form1_Load(Object sender, EventArgs e) in C:\Users\xxx\Desktop\Win10_BrightnessSlider-master\Win10_BrightnessSlider\Form1.cs: Zeile56
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
![image](https://user-images.githubusercontent.com/31684940/70318436-60c89680-1820-11ea-9f21-0bc0c73a0fdc.png)

**Comment by blackholeearth** [comment] 2019-12-06 15:15
Duplicate of system management exceptions . Search issues. 
 Your monitor is not supported by wmi

**Closed by blackholeearth** 2019-12-06 15:15 UTC
