### ISSUE TITLE
No Shortcut on keyboard to adjust brightness. 

### ISSUE THREAD

**Issue by gaurav-js-dev** [blackholeearth/Win10_BrightnessSlider#88] opened 2021-01-16 14:52 UTC
Can you please add a feature where a user can adjust the brightness through keyboard shortcut ??

**Comment by shantanub08** [comment] 2021-01-24 13:27
Looking for the same

**Comment by blackholeearth** [comment] 2021-01-28 20:22
Duplicate of #70 
Follow that please

**Closed by blackholeearth** 2021-01-28 20:22 UTC
