### ISSUE TITLE
how to delete safely? Screen got dim. Cant revert back 

### ISSUE THREAD

**Issue by shavatek** [blackholeearth/Win10_BrightnessSlider#85] opened 2021-01-01 18:29 UTC
My monitor got dimm. The slider will slide but not stay on a setting...like at all. I rather go back

**Comment by blackholeearth** [comment] 2021-01-28 21:49
A) Try emoach monitorian  in github.
B) Twinkle tray.

**Comment by blackholeearth** [comment] 2021-01-28 21:59
Duplicate of #69 

>  The app communicates directly with the monitor to change the settings in the monitor's OSD menu. It has nothing to do with nightlight.

Check the brightness setting in your monitor's OSD menu.

**Closed** 2021-06-14 13:49 UTC
Labels: uninstall-guide
