### ISSUE TITLE
using keyboard shortcuts 

### ISSUE THREAD

**Issue by cl1o1** [blackholeearth/Win10_BrightnessSlider#95] opened 2021-05-12 01:20 UTC
hey, is it possible to add a functionality that allows keyboard shortcuts to interact with the app so that I can use my keyboard shortcuts to change the brightness. thanks :)

**Comment by blackholeearth** [comment] 2021-05-19 07:47
duplicate of #4     and many more

**Closed by blackholeearth** 2021-05-19 07:47 UTC
