### ISSUE TITLE
Exception when adjusting brightness of an inactive display

### ISSUE THREAD

**Issue by laloch** [blackholeearth/Win10_BrightnessSlider#90] opened 2021-02-16 11:57 UTC
Hi, thanks for this tool.

I'm using v1.7.9.
I have my display, which is ultra wide with PIP/PBP function, connected to my PC simultaneously by two cables. The display thus looks to the system as two separate monitors. _Win10_BrightnessSlider_ shows them both as `wmi.C34J79x`. As long as both the outputs are active (display showing image from both inputs in PBP mode) everything works as expected and both sliders adjust display brightness just fine. Once I deactivate one of the outputs and continue using only "Display 1" or "Display 2", an attempt to adjust brightness of the inactive output leads to the exception below. I assume the same happens in a scenario with two physical displays connected and only one of them being active.

```
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Nullable`1.get_Value()
   at Win10_BrightnessSlider.RichInfoScreen.SetBrightness(Int32 value, Boolean _isMouseDown)
   at Win10_BrightnessSlider.uc_brSlider.trackBar1_Scroll(Object sender, EventArgs e)
   at System.Windows.Forms.TrackBar.OnScroll(EventArgs e)
   at System.Windows.Forms.TrackBar.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by blackholeearth** [comment] 2021-02-17 15:11
Duplicate of #35

**Closed** 2021-05-18 08:51 UTC
