### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Iskandare** [blackholeearth/Win10_BrightnessSlider#78] opened 2020-10-29 16:45 UTC
Hi, 
be able to change windows to dark mode from brightnessSlider will be great !

**Comment by seaque** [comment] 2020-11-04 09:54
it's just a brightness slider.

**Comment by blackholeearth** [comment] 2021-01-28 20:32
Duplicate of  #66 

I think I wrote that you have to modify a regular files and it's kind of a hack I really don't want to do it.

**Closed** 2021-01-28 21:53 UTC
