### ISSUE TITLE
Hotkeys

### ISSUE THREAD

**Issue by bovshenkov** [blackholeearth/Win10_BrightnessSlider#45] opened 2019-03-08 16:51 UTC
Hello! Your application works fine with my monitor lg 27uk650-w 4k.
I would really like to change the brightness of the hot keys, is it possible?

**Comment by blackholeearth** [comment] 2019-03-20 11:51
duplicate of #4 

watch  #4    for possibilites

**Closed** 2019-03-20 11:51 UTC
